# Generated by Django 5.0.6 on 2024-06-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
