# Generated by Django 5.0.6 on 2024-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0002_template_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('DROPDOWN', 'Dropdown'), ('MULTISELECT', 'MultiSelect'), ('FILEUPLOAD', 'FileUpload'), ('CURRENCY', 'Currency'), ('PHONE', 'Phone'), ('NAME', 'Name'), ('EMAIL', 'Email'), ('DATE', 'Date')], default='TEXT', max_length=100),
        ),
    ]
