# Generated by Django 5.0.6 on 2024-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0003_alter_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoption',
            name='sort_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
