# Generated by Django 5.0.6 on 2024-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0004_fieldoption_sort_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='allow_specific_file_type',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='file_types',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='field',
            name='maximum_files',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='field',
            name='maximum_size',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='In MB'),
        ),
    ]
