# Generated by Django 5.0 on 2024-11-06 11:25

import dynamic_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0006_section_field_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='variable_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='unique_prefix',
            field=models.CharField(blank=True, default=dynamic_form.models.generate_unique_prefix, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('DROPDOWN', 'Dropdown'), ('MULTISELECT', 'MultiSelect'), ('FILEUPLOAD', 'FileUpload'), ('CURRENCY', 'Currency'), ('PHONE', 'Phone'), ('NAME', 'Name'), ('EMAIL', 'Email'), ('DATE', 'Date'), ('SIGNATURE', 'Signature')], default='TEXT', max_length=100),
        ),
    ]
